# matrix -> all the element from second row

In [1]:
import numpy as np

In [3]:
arr=np.random.randint(1,100,size=(5,5))

In [4]:
arr

array([[11, 16, 52, 73, 49],
       [75,  7, 37,  8, 33],
       [93, 78, 89, 32, 39],
       [39, 14, 47, 19, 93],
       [57, 66, 34, 49, 77]])

In [5]:
arr[1]

array([75,  7, 37,  8, 33])

In [6]:
# all the element from 3rd col

In [8]:
arr[:,2]

array([52, 37, 89, 47, 34])

In [9]:
#from above matrix 3*3 matrix selection
arr[0:3,0:3]

array([[11, 16, 52],
       [75,  7, 37],
       [93, 78, 89]])

In [10]:
# all the element greater than 30

In [11]:
filter = arr>30

In [12]:
filter

array([[False, False,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
arr[filter]

array([52, 73, 49, 75, 37, 33, 93, 78, 89, 32, 39, 39, 47, 93, 57, 66, 34,
       49, 77])

In [14]:
np.where #try

<function where at 0x00000290F3AF5170>

# find all the even element from array

In [15]:
arr1 = np.arange(1,30)

In [16]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
filter = arr1%2==0

In [20]:
filter

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [21]:
arr1[filter]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# replace all multiply of 3 with -1

In [23]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
arr1%3==0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [26]:
np.where(arr1%3==0, -1, arr1 )

array([ 1,  2, -1,  4,  5, -1,  7,  8, -1, 10, 11, -1, 13, 14, -1, 16, 17,
       -1, 19, 20, -1, 22, 23, -1, 25, 26, -1, 28, 29])

In [27]:
# np.where(condition,val1,val2) 

In [28]:
arr.T

array([[11, 75, 93, 39, 57],
       [16,  7, 78, 14, 66],
       [52, 37, 89, 47, 34],
       [73,  8, 32, 19, 49],
       [49, 33, 39, 93, 77]])