In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr+5 # less time

array([6, 7, 8, 9])

In [6]:
arr*23

array([23, 46, 69, 92])

# 2d numpy array 

In [9]:
np.array([[1,2,3,4],[4,6,7,12]])

array([[ 1,  2,  3,  4],
       [ 4,  6,  7, 12]])

In [10]:
mat=np.array([[1,2,3,4],[6,7,8,9]])

In [11]:
type(mat)

numpy.ndarray

In [12]:
mat.ndim

2

In [13]:
mat.shape

(2, 4)

In [14]:
mat.nbytes #total size

32

In [16]:
mat1=np.matrix([[1,2,3],[4,5,6]])

In [17]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
mat1.dtype

dtype('int32')

In [19]:
mat1.flatten()

matrix([[1, 2, 3, 4, 5, 6]])

In [24]:
mat1.flatten('F')

matrix([[1, 4, 2, 5, 3, 6]])

# slicing on 2d array

In [28]:
mat

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

# mat[row,col]

row -> start:end
col -> start : end
    
first process -> row
then col

In [29]:
mat[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [33]:
mat3=np.arange(1,101).reshape(10,10)

In [34]:
mat3

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [35]:
mat3.shape

(10, 10)

In [36]:
#select whole matrix
mat3[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
# select
mat3[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [39]:
mat3[0,1]

2

In [40]:
mat3[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
mat3[0][0] # mat[row][col]

1

In [42]:
mat3[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [44]:
res=mat3[2:6,3:8]

In [45]:
res

array([[24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58]])

In [46]:
res[0][0]

24

# more important function

In [48]:
# ones(row,col)
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [49]:
one=np.ones(7)

In [50]:
one

array([1., 1., 1., 1., 1., 1., 1.])

In [51]:
one.dtype

dtype('float64')

In [52]:
np.ones(7,dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [53]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [55]:
# zeros()
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [56]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [61]:
z=np.zeros((4,5),dtype=int)

In [59]:
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## reshape

In [63]:
arr

array([1, 2, 3, 4])

In [64]:
arr.ndim

1

In [65]:
arr.shape

(4,)

In [68]:
reshape_arr=arr.reshape((2,2)) # reshape(shape,order)
# shape -> (row,col) -> total -> row*col

In [67]:
arr

array([1, 2, 3, 4])

In [69]:
reshape_arr

array([[1, 2],
       [3, 4]])

In [70]:
arr.reshape((3,5))

ValueError: cannot reshape array of size 4 into shape (3,5)

In [71]:
arr.reshape((1,4))

array([[1, 2, 3, 4]])

In [75]:
arr4=arr.reshape((2,2),order='F')

In [76]:
arr4

array([[1, 3],
       [2, 4]])

In [77]:

arr4.flatten()

array([1, 3, 2, 4])

In [78]:
arr4

array([[1, 3],
       [2, 4]])

In [79]:

# ravel() -> convert into 1 d array
arr4.ravel()

array([1, 3, 2, 4])

In [80]:
arr4

array([[1, 3],
       [2, 4]])

# matrix operation

In [81]:
np.arange(2,100) # arange(start,end) -> create of element start to end

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
mat_1=np.arange(1,10).reshape((3,3))

In [85]:
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
mat_2=np.arange(10,19).reshape((3,3))

In [88]:
mat_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [89]:
mat_1+mat_2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [90]:
mat_1 * mat_2 # element wise

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [91]:
mat_1 @mat_2 #matric multiplication

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [92]:
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
mat_1.T # tranpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# concatenate

In [95]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [97]:
np.concatenate((a,b),axis=0) #tab suggestion -> axis -> 0: row .. 1->columns

array([1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
np.concatenate((a,b),axis=1) #must 2d

AxisError: axis 1 is out of bounds for array of dimension 1

In [99]:
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
mat_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [102]:
np.concatenate((mat_1,mat_2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [104]:
np.concatenate((mat_1,mat_2),axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [105]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.arange(1,10,2) #start,stop,step

array([1, 3, 5, 7, 9])

# hstack , vstack

In [108]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [109]:
#hstack -> add col
# hstack((tuple of array))
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [110]:
#vstack -> add row 
#vstack((tuple of array))
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# sum

In [112]:
arr

array([1, 2, 3, 4])

In [113]:
np.sum(arr) #gives sum of arr element

10

In [114]:
a

array([[1, 2],
       [3, 4]])

In [115]:
np.sum(a)

10

In [116]:
np.sum(a,axis=0) # 0> col , 1->row

array([4, 6])

In [117]:
np.sum(a,axis=1)

array([3, 7])

In [118]:
mat3

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [119]:
#max
mat3.max()

100

In [120]:
#row wise max
mat3.max(axis=1)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [121]:
# col wise max
mat3.max(axis=0)

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

# sort

In [124]:
arr5=np.array([4,9,1,5])

In [125]:
arr5

array([4, 9, 1, 5])

In [126]:
np.sort(arr5)

array([1, 4, 5, 9])

In [130]:
mat_3=np.array([[5,15,4],[7,19,11],[29,3,67]])

In [131]:
mat_3

array([[ 5, 15,  4],
       [ 7, 19, 11],
       [29,  3, 67]])

In [132]:
np.sort(mat_3) #by default sort -> row wise

array([[ 4,  5, 15],
       [ 7, 11, 19],
       [ 3, 29, 67]])

In [133]:
np.sort(mat_3,axis=0) #col wise sort

array([[ 5,  3,  4],
       [ 7, 15, 11],
       [29, 19, 67]])

In [134]:
# np.cumsum () -> commuculative sum

In [135]:
np.cumsum(arr5)

array([ 4, 13, 14, 19])

In [136]:
np.cumsum(mat_3,axis=1) # row wise

array([[ 5, 20, 24],
       [ 7, 26, 37],
       [29, 32, 99]])

In [137]:
 np.cumsum(mat_3,axis=0) #col wise

array([[ 5, 15,  4],
       [12, 34, 15],
       [41, 37, 82]])