In [1]:
import numpy as np

# linespace
# logspace
# split
# advanced math -> linear alzebra

In [3]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [4]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [5]:
np.linspace(1,100,10,dtype=int)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

## Logspace

In [6]:
np.logspace(1,100)

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

# random number

In [9]:
np.random.rand() # gives one random 0 to 1

0.45308344672592626

In [10]:
# np.random.randint(st,end,size)
np.random.randint(1,100)

86

In [14]:
np.random.randint(10,100,2)

array([57, 16])

In [17]:
np.random.randint(10,100,(3,4)) #(3,4) 3: row , col:4

array([[49, 59, 69, 89],
       [56, 86, 81, 53],
       [24, 90, 70, 24]])

# Linear algbra

In [18]:
# 3x+y = 9 , x+2y = 8

a = np.array([[3, 1], [1, 2]])

b= np.array([9, 8])

In [19]:
a

array([[3, 1],
       [1, 2]])

In [20]:
b

array([9, 8])

In [21]:
np.linalg.solve(a,b)

array([2., 3.])

In [22]:
np.linalg.inv(a)

array([[ 0.4, -0.2],
       [-0.2,  0.6]])

In [23]:
np.linalg.det(a)

5.000000000000001

In [24]:
np.linalg.eig(a)

EigResult(eigenvalues=array([3.61803399, 1.38196601]), eigenvectors=array([[ 0.85065081, -0.52573111],
       [ 0.52573111,  0.85065081]]))